name: Security Review

permissions:
  pull-requests: write
  contents: read

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2

      # (необязательно) префлайт-проверка ключа
      - name: Preflight Anthropic key
        env:
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          test -n "$ANTHROPIC_API_KEY" || (echo "ANTHROPIC_API_KEY is empty"; exit 2)
          echo "Key present ✔"

      - name: Run Claude Code Security Review
        uses: anthropics/claude-code-security-review@main
        with:
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}   # input для самого action
          comment-pr: true
          run-every-commit: true
          exclude-directories: "node_modules,dist,build,.next,venv,.venv,__pycache__"
        env:
          # ⬅️ это важно: Claude Code CLI ждёт именно ANTHROPIC_API_KEY
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
